title: "Scholarly Report"
description: "A simple static site using GitHub Pages"
baseurl: "/scholarly-report" # the subpath of your site
url: "https://YOUR-USERNAME.github.io" # the base hostname & protocol for your site
