name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/react-vite

      - name: Build project
        env:
          BASE_API: ${{ secrets.PUBLIC_IP_SERVER }}
        run: npm run build
        working-directory: ./frontend/react-vite

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./frontend/react-vite/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./frontend/react-vite/dist

      - name: List files after downloading artifact (debugging)
        run: ls -la ./frontend/react-vite/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/react-vite/dist

      - name: Test SPARQL API
        run: curl -k -s -o /dev/null -w "%{http_code}" https://${{ secrets.SPARQL_API }} | grep -q "200"
        if: success()

      - name: Test Statistics API
        run: curl -k -s -o /dev/null -w "%{http_code}" https://${{ secrets.STATISTICS_API }} | grep -q "200"
        if: success()
